name: Docker Build Example

on:
  push:
    branches: [ "main", "master" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t automation-app:latest ./docker

      - name: Run container test
        run: |
          docker run --rm automation-app:latest echo "Docker build successful"

      # OPTIONAL: Push to GitHub Container Registry
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push Image
      #   run: |
      #     docker tag automation-app:latest ghcr.io/${{ github.repository_owner }}/automation-app:latest
      #     docker push ghcr.io/${{ github.repository_owner }}/automation-app:latest
